-- Customer Data Analysis Queries

-- 1. Shopping distribution by gender
SELECT
    gender,
    COUNT(*) AS total_purchases
FROM customer_data
GROUP BY gender;

-- 2. Products sold by gender
SELECT
    gender,
    SUM(quantity) AS total_products_sold
FROM customer_data
GROUP BY gender;

-- 3. Revenue generated by gender
SELECT
    gender,
    SUM(revenue) AS total_revenue
FROM customer_data
GROUP BY gender;

-- 4. Shopping distribution by age group
SELECT
    age_group,
    COUNT(*) AS total_purchases
FROM customer_data
GROUP BY age_group;

-- 5. Revenue generated by age group
SELECT
    age_group,
    SUM(revenue) AS total_revenue
FROM customer_data
GROUP BY age_group;

-- 6. Category-wise revenue
SELECT
    category,
    SUM(revenue) AS total_revenue
FROM customer_data
GROUP BY category
ORDER BY total_revenue DESC;

-- 7. Payment method distribution
SELECT
    payment_method,
    COUNT(*) AS total_transactions
FROM customer_data
GROUP BY payment_method;
